### ISSUE TITLE
!ops command

### ISSUE THREAD

**Issue by Mikaela** [DarthGandalf/znclinker#13]
As #znc follows the freenode policy and doesn't have ops opped, people can have difficulties in deciding whom to contact when there is an issue. ZNC-linker could have !ops command which many people try when they are unsure.

* `!ops [<optional message>]`
    * would either ping all the ops on channel or send a PM (still involving the nick in order to cause highlight in some clients).

See also:

* https://mikaela.info/english/2015/04/01/keep-the-ops-opped.html

**Comment by Mikaela** [comment]
I am not sure if this would solve anything though or would there just have to be more ops.

**Comment by DarthGandalf** [comment]
Yes, mass highlight, or even better, mass privmsg...
Why would that be good?

**Comment by DarthGandalf** [comment]
As for the policy, how other channel handle this? By people looking at /cs access #znc list?

**Comment by Mikaela** [comment]
So people can alert ops without having to know who the ops are when there is trouble.

Other channels handle this by not knowing /cs access and going to talk to #freenode or using !ops which is either handled by bot of that channel or #AntiSpamMeta bot (which might be worth asking to #znc).

With #znc `/cs access` still works when people know to use it, because there aren't as many ops and you don't have to figure out who is present and who isn't.

**Comment by DarthGandalf** [comment]
> would there just have to be more ops
Done.

I'm not sure such !ops would be very good, but you can add it, I guess. I won't list any people there without their explicit approval though.

>  #AntiSpamMeta bot (which might be worth asking to #znc).

Please do, if that bot helps.

**Comment by KindOne-** [comment]
```!ops``` command can be used for abuse/mass highlighting the ops, some trolls just love doing ```!ops```.

**Comment by Mikaela** [comment]
> Please do, if that bot helps.

Done, now that it's admins just wake up :)

> !ops command can be used for abuse/mass highlighting the ops, some trolls just love doing !ops

Nothing prevents removing them.

**Comment by ilbelkyr** [comment]
>>#AntiSpamMeta bot (which might be worth asking to #znc).
>
>Please do, if that bot helps.

(@Mikaela poked us in `#antispammeta`; we tend to make sure the channel founder agrees, but @DarthGandalf confirming should be sufficient as well.)

Do keep in mind AntiSpamMeta mostly detects common patterns of spam/flooding (and `!ops`) and pings the relevant ops in `#antispammeta`; that said, I can definitely see it being useful for a channel as big as `#znc`.

If that sounds OK to you, feel free to poke me (here or on IRC, either works) with further information (exactly whom to ping / whether there's an -ops channel for `#znc` you'd like AntiSpamMeta to report things to / any channel bots it should *not* trigger on) and I'll set it up for you if you'd like. (If you decide against it, that's OK too, obviously.)

**Comment by Mikaela** [comment]
In case you are interested, I attach the original request:

> Hi, could we get AntiSpamMeta to #znc ? https://github.com/DarthGandalf/znclinker/issues/13#issuecomment-136160823 The people who should be pinged by !ops in case they come here are fred`` (fred_2), psychon, Dessa, DarthGandalf, jpnurmi, MetaNova, kerio, Mikaela. (Sorry if there is some ususal procedure for asking and I have missed it)

Later after I got home I added to the question on bots:

> I should probably add that there is only one bot, ZNC-linker, but I htink it's unlikely for it to triggerr AntiSpamMeta

(I seriously should use some other keyboard or check my typing better, maybe even load spell checker plugin.)

**Comment by DarthGandalf** [comment]
AntiSpamMeta is set now, pinging Mikaela only. If someone else wants to be pinged, ask on #antispammeta.
